name: space_memory
channels:
  - pytorch
  - default
  - conda-forge
dependencies:
  - python 3.7.1
  - ssl
  - pip
  - conda-forge
  - cudnn
  - pytorch 
  - torchvision
  - matplotlib
  - conda:
    - numpy
    - pandas
    - pytorch
    - torchvision
    - namedlist
  - pip:
    - ray
    - psutil
    - setproctitle
    - matplotlib
    - gym
    - gym[classic_control]
    - gym[box2d]
  
