name: space_memory
channels:
  - pytorch
  - default
  - conda-forge
dependencies:
  - python 3.7.1
  - ssl
  - conda-forge
  - cudatoolkit 9
  - cudnn
  - pytorch 
  - torchvision
  - matplotlib
  - conda:
    - numpy
    - pandas
    - pytorch
    - torchvision
  
