//
// Created by SoliareofAstora on 25.02.2020.
//

#ifndef SPACE_ENVIRO_RENDERING_OBSERVATIONS_RENDER_DISTANCE_HPP_
#define SPACE_ENVIRO_RENDERING_OBSERVATIONS_RENDER_DISTANCE_HPP_
namespace rendering{
} // namespace rendering

#endif //SPACE_ENVIRO_RENDERING_OBSERVATIONS_RENDER_DISTANCE_HPP_
